server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/casadocodigo
    username: keycloak
    password: keycloak
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/
    schemas: casadocodigo
    user: keycloak
    password: keycloak
          
security: 
  jwt: 
    expiracao: 50
    chave-assinatura: casadocodigoassinaturatokenjwt
